trigger:
  - main  # or your branch name

pool:
  name: MySelfHostedPool # ✅ Your self-hosted agent name

steps:
  # Step 1: Install dependencies
  - task: Npm@1
    displayName: 'Install Dependencies'
    inputs:
      command: 'install'

  # Step 2: Run build
  - task: Npm@1
    displayName: 'npm build'
    inputs:
      command: 'custom'
      customCommand: 'run build'

  # Step 3: Publish build artifacts
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    inputs:
      PathtoPublish: 'build'
      ArtifactName: 'drop'
      publishLocation: 'Container'

  # Step 4: Deploy to Azure Web App on Linux
  - task: AzureWebApp@1
    displayName: 'Deploy to Azure Web App'
    inputs:
      azureSubscription: 'Azure subscription 1 (ba64d9a9-d968-4e97-af3e-b764ec14bf8d)'  # Replace with your Azure DevOps service connection
      appType: 'webAppLinux'
      appName: 'sandeepyoutube'                   # Replace with your Azure Web App name
      package: '$(System.DefaultWorkingDirectory)/build'
      runtimeStack: 'STATICSITE|1.0'
